DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;

USE bd;

CREATE TABLE JUGADOR (
	ID INT NOT NULL,
	USERNAME VARCHAR(30),
	PASSWOORD VARCHAR(40),
	ESTADO VARCHAR(10),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE PARTIDA (
	IDJUGADOR1 INT NOT NULL,
	IDJUGADOR2 INT NOT NULL,
	IDPARTIDA INT NOT NULL,
	FECHA_Y_HORA VARCHAR(60),
	DURACION_PARTIDA INT,
	GANADOR VARCHAR(30),
	PRIMARY KEY (IDPARTIDA)

)ENGINE=InnoDB;


INSERT INTO JUGADOR VALUES (1, 'Juan', '123', 'Online');
INSERT INTO JUGADOR VALUES (2, 'Maria', 'aaaa', 'Online');
INSERT INTO JUGADOR VALUES (3, 'Pepe', '1134', 'Offline');
INSERT INTO JUGADOR VALUES (4, 'Jose', '1afafaf', 'Online');
